---
theme                    : jekyll-theme-cayman
title                    : UCLA Anderson MFE (2021-22) BootCamp
title_separator          : "-"
subtitle                 : Group 23
description              : Aman Jindal | Yuhang Jiang | Daniel Gabriel Tan | Qining Liu
---
