theme: jekyll-theme-cayman
title: "UCLA Anderson MFE (2021-22) BootCamp"
description: "Group 23: Aman Jindal | Yuhang Jiang | Daniel Gabriel Tan | Qining Liu"

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax

